# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: book_shelf
  host: localhost
  username: dxmc
  password: dxmc_mc_123123


test:
  <<: *default
  database: book_shelf_test

production:
  <<: *default
  database: book_shelf_prod
